"use client";
import React, { createContext, useContext, useEffect, useState } from "react";
import { useAuth } from "@/contexts/AuthContext";

type Lang = "en" | "ar";
interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  toggleLang: () => void;
  t: (key: string) => string;
}
const LanguageContext = createContext<LanguageContextType | null>(null);
const LANG_STORAGE_KEY = "drc-lang";
const LANG_EVENT = "drc:lang-change";

type SiteContentRow = {
  key: string;
  en: string | null;
  ar: string | null;
};

export const baseTranslations: Record<Lang, Record<string, string>> = {
  en: {
    // ── Navigation ────────────────────────────────────────────────────────────
    "nav.about": "About",
    "nav.projects": "Projects",
    "nav.workshops": "Workshops",
    "nav.events": "Events",
    "nav.team": "Team",
    "nav.alumni": "Alumni",
    "nav.signin": "Sign In",
    "nav.joinus": "Join Us",
    "nav.dashboard": "Dashboard",

    // ── Home ─────────────────────────────────────────────────────────────────
    "home.hero.kicker": "Student-built robotics. Public proof.",
    "home.status": "On Mission",
    "home.hero1": "Where ambition",
    "home.hero2": "takes flight.",
    "home.sub": "A King Saud University student club empowering innovation and technical skill in drones and robotics, aligned with Saudi Vision 2030.",
    "home.tagline": "نبتكر لنحلّق — Drones & Robotics Club, KSU.",
    "home.cta.join": "Join DRC",
    "home.cta.projects": "Explore Projects",
    "home.cta.workshops": "Browse Workshops",
    "home.cta.partner": "Partner Contact",
    "home.cta1": "Get Involved",
    "home.cta2": "View Our Work →",
    "home.proof.systems": "Systems stack",
    "home.proof.output": "Visible output",
    "home.proof.output.value": "Projects, workshops, demos",
    "home.proof.partner": "Company contact",
    "home.paths.label": "Start Here",
    "home.paths.title": "Choose the right way in.",
    "home.paths.desc": "Different visitors come for different reasons. These are the fastest routes into DRC.",
    "home.paths.join.label": "For future members",
    "home.paths.join.title": "Join the club",
    "home.paths.join.desc": "Apply, pick your department, and start building with the team.",
    "home.paths.join.cta": "Apply in minutes",
    "home.paths.projects.label": "For visitors",
    "home.paths.projects.title": "Explore projects",
    "home.paths.projects.desc": "See the systems, prototypes, and software our members are shipping.",
    "home.paths.projects.cta": "See current work",
    "home.paths.workshops.label": "For learners",
    "home.paths.workshops.title": "Browse workshops",
    "home.paths.workshops.desc": "Watch recordings or register for live sessions and build skills quickly.",
    "home.paths.workshops.cta": "Start learning",
    "home.announcements.label": "Announcements",
    "home.announcements.title": "What the club needs you to notice now",
    "home.announcements.desc": "Pinned updates, high-signal announcements, and fast context for visitors who want the latest state of the club.",
    "home.mediawall.label": "Media Wall",
    "home.mediawall.title": "Proof that the club is active",
    "home.mediawall.desc": "A mixed wall of reels, project imagery, event coverage, and announcement visuals so visitors can scan the club in seconds.",
    "home.mediawall.emptyTitle": "The media wall is waiting on fresh visuals",
    "home.mediawall.emptyBody": "As soon as new public photos, reels, event banners, or announcement images are published, they will land here.",
    "home.mediawall.cta": "Open related page",
    "home.mediawall.badge.reel": "Reel",
    "home.mediawall.badge.photo": "Photo",
    "home.mediawall.badge.video": "Video",
    "home.mediawall.badge.post": "Post",
    "home.mediawall.badge.project": "Project",
    "home.mediawall.badge.event": "Event",
    "home.mediawall.badge.announcement": "Announcement",
    "home.signal.event": "Next Event",
    "home.signal.event.empty": "No event yet",
    "home.signal.event.detail": "The next published club event will appear here.",
    "home.signal.media": "Media Feed",
    "home.signal.media.empty": "Quiet",
    "home.signal.media.detail": "Fresh visual posts are live on the homepage.",
    "home.signal.media.detailEmpty": "No published visual update is visible right now.",
    "home.signal.join": "Member Intake",
    "home.signal.join.open": "Open",
    "home.signal.join.closed": "Paused",
    "home.signal.join.detailOpen": "Applications are currently being accepted.",
    "home.signal.join.detailClosed": "The next intake window has not opened yet.",
    "home.pulse.label": "Club Pulse",
    "home.pulse.title": "What is active this week across departments",
    "home.pulse.desc": "A lightweight read on which teams are moving, where the momentum is, and what is visible on the public surface right now.",
    "home.pulse.thisWeek": "This Week",
    "home.pulse.state.high": "High",
    "home.pulse.state.medium": "Tracking",
    "home.pulse.state.quiet": "Quiet",
    "home.motm.label": "Spotlight",
    "home.motm.title": "Members of the Month",
    "home.motm.desc": "Recognized this month for outstanding contributions.",
    "home.motm.viewteam": "View full team →",
    "home.admin.manage": "Manage →",
    "admin.manage": "Manage →",
    "stats.projects": "Projects Built",
    "stats.competitions": "Competitions Won",
    "stats.members": "Active Members",
    "stats.departments": "Departments",
    "section.story.label": "Flagship Work",
    "section.story.title": "A club that feels active because the work is visible.",
    "section.story.desc": "Featured blocks let media and leaders show what members are building, learning, and publishing without touching code.",
    "section.whatwedo.label": "What We Do",
    "section.whatwedo.title": "More Than a Club",
    "section.whatwedo.desc": "We're a community of builders, coders, storytellers, and organizers bringing ambitious ideas to life together.",
    "section.workshops.label": "Learning",
    "section.workshops.title": "Workshop Recordings",
    "section.workshops.desc": "Missed a session? Catch up on all our recorded workshops — from drone assembly to AI and beyond.",
    "section.workshops.viewall": "View All →",
    "section.projects.label": "Featured",
    "section.projects.title": "Latest Projects",
    "section.projects.desc": "A glimpse at what our teams are building right now.",
    "section.projects.viewall": "View All →",
    "section.cta.title": "Ready to build the future?",
    "section.cta.desc1": "Engineer, code, and compete with the technical teams.",
    "section.cta.desc2": "Tell our story, run our events, grow our community.",
    "section.cta.apply": "Apply Now",
    "section.cta.learn": "Learn More →",
    "project.status.completed": "Completed",
    "project.status.inprogress": "In Progress",
    "project.status.planned": "Planned",
    "workshop.watch": "Watch Recording",
    "workshop.duration": "min",
    "highlight.innovation.title": "Innovation",
    "highlight.innovation.desc": "Drones, robotics, and R&D — where our members prototype ideas and take them to national and international competitions.",
    "highlight.development.title": "Development",
    "highlight.development.desc": "Software, apps, and platforms — the code that powers our autonomous systems and the tools our members ship.",
    "highlight.community.title": "Community",
    "highlight.community.desc": "Media, PR, HR, logistics, and Madarat — the people-side of the club that makes everything else possible.",
    "scroll": "Scroll",

    // ── About ─────────────────────────────────────────────────────────────────
    "about.hero.label": "About DRC",
    "about.hero.title": "From DAAS to DRC —",
    "about.hero.accent": "four years airborne",
    "about.hero.desc": "Founded in 2022 as DAAS (Drones & Autonomous Systems), today the Drones & Robotics Club is one of King Saud University's largest engineering communities — building, training, and competing across nine departments.",
    "about.vision.title": "Our Vision",
    "about.vision.body": "To be Saudi Arabia's leading student community for drones and autonomous systems — developing builders, communicators, and leaders who carry Vision 2030 forward through real engineering work.",
    "about.vision.tagline": "أن نكون المجتمع الطلابي الرائد للدرونز والأنظمة الذاتية في المملكة",
    "about.mission.title": "Our Mission",
    "about.mission.body": "Empower every member — engineer, designer, communicator, organiser — with real skills, hands-on experience, and a community that turns ambition into flight.",
    "about.mission.tagline": "تمكين الابتكار وتعزيز المهارات التقنية، تماشيًا مع رؤية المملكة 2030",
    "about.values.label": "Our Values",
    "about.values.title": "What Drives Us",
    "about.values.innovation.title": "Innovation First",
    "about.values.innovation.desc": "We don't follow templates. Every project, event, and idea is a chance to push past the expected and build something better.",
    "about.values.community.title": "Community Driven",
    "about.values.community.desc": "Knowledge grows when shared. Our culture of mentorship and collaboration turns beginners into builders and builders into leaders.",
    "about.values.competition.title": "Competition Ready",
    "about.values.competition.desc": "We train to win. From local hackathons to international robotics championships, we bring our best every time.",
    "about.depts.label": "Structure",
    "about.depts.title": "Our Departments",
    "about.depts.desc": "Nine specialized departments working together to deliver innovation at every level.",
    "dept.executive.name": "Executive",
    "dept.executive.desc": "Club leadership, strategy, and cross-department coordination",
    "dept.hr.name": "Human Resources",
    "dept.hr.desc": "Recruitment, onboarding, and member development",
    "dept.development.name": "Development",
    "dept.development.desc": "Software, apps, platforms, and AI systems",
    "dept.innovation.name": "Innovation",
    "dept.innovation.desc": "Drones, robotics, R&D, and competition builds",
    "dept.media.name": "Media",
    "dept.media.desc": "Content creation, photography, and visual branding",
    "dept.pr.name": "Public Relations",
    "dept.pr.desc": "External partnerships, sponsorships, and outreach",
    "dept.finance.name": "Finance",
    "dept.finance.desc": "Budgets, funding, and financial planning",
    "dept.logistics.name": "Logistics",
    "dept.logistics.desc": "Events, equipment management, and operations",
    "dept.madarat.name": "Madarat",
    "dept.madarat.desc": "Member upskilling, workshops, and educational initiatives",
    "about.timeline.label": "Our Journey",
    "about.timeline.title": "Growing Year by Year",
    "about.timeline.2020.event": "Club founded",
    "about.timeline.2020.detail": "Started as a small group of drone and robotics enthusiasts with 15 founding members",
    "about.timeline.2021.event": "First competition entry",
    "about.timeline.2021.detail": "Competed in our first national robotics challenge and placed in the top 5",
    "about.timeline.2022.event": "Departmental restructure",
    "about.timeline.2022.detail": "Organized into dedicated teams to scale our impact and serve more members",
    "about.timeline.2023.event": "International debut",
    "about.timeline.2023.detail": "Competed in regional drone racing and robotics leagues for the first time",
    "about.timeline.2024.event": "Fastest-growing club on campus",
    "about.timeline.2024.detail": "Reached 77+ active members across nine departments",
    "about.timeline.2025.event": "Research & industry partnerships",
    "about.timeline.2025.detail": "Collaborating with organizations on real-world autonomous systems projects",

    // ── Team ──────────────────────────────────────────────────────────────────
    "team.hero.label": "Team",
    "team.hero.title": "The People Behind",
    "team.hero.accent": "the Club",
    "team.hero.desc": "Meet the builders, creators, organizers, and leaders powering DRC across nine departments.",
    "team.stats.members": "Active Members",
    "team.stats.departments": "Departments",
    "team.stats.officers": "Officers",
    "team.executive.label": "Executive",
    "team.executive.title": "Club Leadership",
    "team.executive.desc": "The president, vice presidents, and projects supervisor steering DRC's vision and operations.",
    "team.depts.label": "Departments",
    "team.depts.title": "Department Leadership",
    "team.depts.desc": "Each department is led by a leader and vice leader working in tandem.",
    "team.qa.title": "Quality & Assurance",
    "team.qa.desc": "Three QA leaders embedded within Innovation to uphold standards across all builds.",
    "team.role.president": "President",
    "team.role.vp": "Vice President",
    "team.role.supervisor": "Projects Supervisor",
    "team.role.leader": "Department Leader",
    "team.role.vice": "Vice Leader",
    "team.role.co_leader": "Co-Leader",
    "team.role.qa_leader": "QA Leader",
    "team.role.sub_leader": "Sub-Leader",
    "team.placeholder.name": "—",
    "team.motm.label": "Recognition",
    "team.motm.title": "Members of the Month",
    "team.motm.desc": "Exceptional members recognized each month for their contributions across the club.",
    "team.motm.empty": "Members are selected each month by the leadership team.",
    "team.motm.emptyTitle": "Recognition will appear here",
    "team.join.title": "Become Part of the Team",
    "team.join.desc": "Whether you build, code, create, or organize — there's a department for you.",
    "team.join.cta": "Apply Now →",
    "team.alumni.label": "Alumni",
    "team.alumni.title": "Our Alumni",
    "team.alumni.desc": "Members who have graduated and moved on — forever part of the DRC story.",
    "team.alumni.empty": "Alumni profiles coming soon.",
    "team.alumni.emptyTitle": "Alumni profiles are not published yet",
    "team.anchor.label": "Jump To",
    "team.anchor.departments": "Departments",
    "team.anchor.directory": "Directory",
    "team.anchor.recognition": "Recognition",
    "team.anchor.alumni": "Alumni",
    "team.deptmoments.label": "Department Moments",
    "team.deptmoments.title": "Each department has its own rhythm",
    "team.deptmoments.desc": "Different teams carry different responsibilities. This gives visitors a faster read on how the club actually operates.",
    "team.deptmoments.need": "Current Need",
    "team.dept.need.hr": "Recruitment coordination, member care, and reliable onboarding follow-through.",
    "team.dept.need.development": "Product-minded builders who can ship tools, dashboards, and integrations.",
    "team.dept.need.innovation": "Prototype builders who can iterate on hardware, controls, and testing loops.",
    "team.dept.need.media": "Photographers, editors, and storytellers who can make the work visible.",
    "team.dept.need.pr": "Operators who can strengthen partnerships, outreach, and event promotion.",
    "team.dept.need.finance": "Clear budgeting, sponsorship tracking, and disciplined procurement workflows.",
    "team.dept.need.logistics": "Event-ready planners who can manage equipment, setup, and operations calmly.",
    "team.dept.need.madarat": "Learning designers who can turn club knowledge into repeatable training.",

    // ── Join ──────────────────────────────────────────────────────────────────
    "join.hero.label": "Membership",
    "join.hero.title": "Be part of the",
    "join.hero.accent": "creators' community",
    "join.hero.desc": "If your ambition lives in drones, robotics, or autonomous systems — your place is here. Apply, choose your committee, and start building.",
    "join.closed.badge": "Closed",
    "join.benefits.label": "Benefits",
    "join.benefits.title": "Why Join DRC?",
    "join.benefits.desc": "More than a line on your resume — an experience that shapes your career and your community.",
    "join.benefit.experience.title": "Hands-On Experience",
    "join.benefit.experience.desc": "Build real projects — drones, robots, software, events, and community initiatives — not just theory.",
    "join.benefit.compete.title": "Compete & Excel",
    "join.benefit.compete.desc": "Represent your university in national and regional competitions across robotics and innovation.",
    "join.benefit.community.title": "Community & Mentorship",
    "join.benefit.community.desc": "Learn from experienced members and collaborate with motivated peers across every discipline.",
    "join.benefit.workshops.title": "Workshops & Training",
    "join.benefit.workshops.desc": "Regular sessions on electronics, programming, design, media, and more.",
    "join.benefit.career.title": "Career Opportunities",
    "join.benefit.career.desc": "Build a portfolio, expand your network, and connect with industry sponsors.",
    "join.benefit.equipment.title": "Access to Resources",
    "join.benefit.equipment.desc": "Use our lab, tools, 3D printers, flight simulators, and testing facilities.",
    "join.process.label": "Process",
    "join.process.title": "How to Join",
    "join.process.desc": "Four simple steps to becoming a DRC member.",
    "join.step1.title": "Fill Out the Application",
    "join.step1.desc": "Complete the form below with your background, interests, and preferred department.",
    "join.step2.title": "Attend an Orientation",
    "join.step2.desc": "Join one of our orientation sessions to meet the team and see our workspace.",
    "join.step3.title": "Join a Department",
    "join.step3.desc": "Get matched with a department based on your skills and interests.",
    "join.step4.title": "Start Contributing",
    "join.step4.desc": "Dive into projects, attend workshops, and start your journey with DRC.",
    "join.form.label": "Apply",
    "join.form.title": "Application Form",
    "join.form.desc": "Fill out the form and we'll be in touch. Applications are reviewed on a rolling basis.",
    "join.form.name": "Full Name",
    "join.form.name.placeholder": "Your full name",
    "join.form.id": "Student ID",
    "join.form.id.placeholder": "e.g. 44XXXXXXX",
    "join.form.email": "Email",
    "join.form.email.placeholder": "your@email.com",
    "join.form.phone": "Phone Number",
    "join.form.phone.placeholder": "e.g. 05XXXXXXXX",
    "join.form.major": "Major / Field of Study",
    "join.form.major.placeholder": "e.g. Computer Engineering",
    "join.form.dept": "Preferred Department",
    "join.form.dept.placeholder": "Select a department",
    "join.form.motivation": "Why do you want to join DRC?",
    "join.form.motivation.placeholder": "Tell us about your interests, experience, and what you hope to contribute...",
    "join.form.skills": "Relevant Skills",
    "join.form.skills.optional": "(Optional)",
    "join.form.skills.placeholder": "e.g. Python, Arduino, CAD, Video Editing, Event Planning",
    "join.form.submit": "Submit Application",
    "join.form.submitting": "Submitting…",
    "join.form.consent": "By submitting, you agree to be contacted by DRC about your application.",
    "join.readiness.label": "Before you submit",
    "join.readiness.title": "Application readiness",
    "join.readiness.desc": "A strong application gives the team enough context to place you well.",
    "join.readiness.progress": "Form progress",
    "join.readiness.identity": "Your name and contact details are filled in",
    "join.readiness.dept": "You selected the department you want to start in",
    "join.readiness.context": "You added academic context like major or university ID",
    "join.readiness.motivation": "Your motivation explains what you want to learn or contribute",
    "join.readiness.skills": "You included skills or interests the team can build on",
    "join.readiness.selected": "Selected department",
    "join.readiness.selected.empty": "Choose a department to tailor your application.",
    "join.readiness.selected.hint": "You can still collaborate across departments later.",
    "join.expectations.label": "After you submit",
    "join.expectations.title": "What happens next",
    "join.expectations.desc": "Your application enters the HR review queue, then moves to the right team.",
    "join.expectations.step1.title": "Application received",
    "join.expectations.step1.desc": "Your details are stored immediately and marked as pending.",
    "join.expectations.step2.title": "HR review queue",
    "join.expectations.step2.desc": "The HR team reviews background, motivation, and department preference.",
    "join.expectations.step3.title": "Department fit",
    "join.expectations.step3.desc": "Leaders use your interests and skills to route you toward the best starting point.",
    "join.expectations.step4.title": "Next-step contact",
    "join.expectations.step4.desc": "Selected applicants are contacted with the next step, such as orientation or onboarding details.",
    "join.success.title": "Application Received!",
    "join.success.desc": "Thank you for applying to DRC. We'll review your application and reach out to you soon.",
    "join.success.reference": "Reference",
    "join.success.next": "What happens next",
    "join.success.timelineIntro": "Your application is now in the review flow.",
    "join.success.keep": "Keep this reference if you need to follow up with the team.",
    "join.success.cta": "Back to Home",
    "join.error.generic": "Something went wrong. Please try again.",
    "join.faq.label": "FAQ",
    "join.faq.title": "Common Questions",
    "join.faq.q1": "Do I need prior experience?",
    "join.faq.a1": "Not at all! We welcome complete beginners. Our workshop program is designed to bring you up to speed, and every department has experienced mentors ready to help.",
    "join.faq.q2": "What's the time commitment?",
    "join.faq.a2": "Most members spend 4–6 hours per week on club activities — meetings, workshops, and project work. Competition seasons may require more.",
    "join.faq.q3": "Which departments can I join?",
    "join.faq.a3": "We have seven departments open to general members: Innovation, Development, Media, Public Relations, Human Resources, Finance, and Logistics. You can express your preference in the application.",
    "join.faq.q4": "Is there a membership fee?",
    "join.faq.a4": "DRC is free to join. Some specialized workshops or competition travel may have associated costs, which are often subsidized by our sponsors.",
    "join.faq.q5": "Can I be in multiple departments?",
    "join.faq.a5": "You'll be assigned to one primary department, but cross-department collaboration is common and encouraged on most projects.",

    // ── Events ───────────────────────────────────────────────────────────────
    "events.hero.label": "Events",
    "events.hero.title": "Compete. Learn.",
    "events.hero.accent": "Build Together.",
    "events.hero.desc": "From high-stakes drone races to hands-on workshops — our events are where skills are forged and legends are made.",
    "events.upcoming.label": "Upcoming",
    "events.upcoming.title": "What's Next",
    "events.upcoming.desc": "Mark your calendars. These are the events you don't want to miss.",
    "events.upcoming.empty": "No upcoming events scheduled right now. Check back soon.",
    "events.upcoming.seats": "seats left",
    "events.upcoming.seats_full": "Fully booked",
    "events.hours.label": "Credit Hours",
    "events.hours.available": "Available to members after the event",
    "events.hours.confirm": "Confirm Attendance",
    "events.hours.pending": "Attendance pending HR approval",
    "events.hours.approved": "Attendance approved",
    "events.hours.rejected": "Attendance rejected",
    "events.hours.locked": "Confirmations open after the event ends",
    "events.hours.success": "Attendance submitted for HR approval.",
    "events.hours.error": "Could not confirm attendance. Please try again.",
    "events.hours.submitting": "Submitting…",
    "events.achievements.label": "Track Record",
    "events.achievements.title": "Proven on the Field",
    "events.achievements.desc": "Our competition history speaks for itself — highlights from our journey so far.",
    "events.recent.label": "Recap",
    "events.recent.title": "Recent Events",
    "events.recent.desc": "A look back at our latest gatherings, workshops, and competitions.",
    "events.recent.empty": "No past events to show yet.",
    "events.type.competition": "Competition",
    "events.type.workshop": "Workshop",
    "events.type.meetup": "Meetup",
    "events.type.general": "Event",
    "events.cta.workshops": "Browse all workshops →",

    // ── Dashboard ────────────────────────────────────────────────────────────
    "dashboard.overview.title": "Welcome back",
    "dashboard.overview.member": "member",
    "dashboard.overview.desc": "A live view of what matters today across your work, hours, events, and announcements.",
    "dashboard.overview.partial": "Some live dashboard data could not be loaded. The page is showing what is available.",
    "dashboard.stats.members": "Active Members",
    "dashboard.stats.projects": "Active Projects",
    "dashboard.stats.events": "Upcoming Events",
    "dashboard.stats.departments": "Departments",
    "dashboard.today.label": "Today View",
    "dashboard.today.title": "What deserves attention first",
    "dashboard.today.desc": "One place for your next event, open tasks, current hours, and follow-up items.",
    "dashboard.nextEvent.label": "Next Event",
    "dashboard.nextEvent.emptyTitle": "No upcoming event yet",
    "dashboard.nextEvent.emptyBody": "When a new club event is published, it will show up here with time and location details.",
    "dashboard.nextEvent.fallback": "Event details will appear here once the organizers add the full brief.",
    "dashboard.nextEvent.cta": "Open events",
    "dashboard.hours.label": "Volunteer Hours",
    "dashboard.hours.approved": "Approved entries",
    "dashboard.hours.pending": "Pending review",
    "dashboard.quickLinks.label": "Quick Links",
    "dashboard.quickLinks.department": "Open my department space",
    "dashboard.quickLinks.profile": "Update my profile",
    "dashboard.actions.label": "Action Queue",
    "dashboard.actions.title": "What needs action",
    "dashboard.actions.tasks.title": "Open assigned tasks",
    "dashboard.actions.tasks.body": "You still have {count} active tasks that need movement.",
    "dashboard.actions.hours.title": "Hours waiting review",
    "dashboard.actions.hours.body": "{count} logged hour entries are still pending approval.",
    "dashboard.actions.event.title": "Prepare for the next event",
    "dashboard.actions.clear.title": "You are caught up",
    "dashboard.actions.clear.body": "No urgent blockers right now. This is a good time to explore current projects or workshops.",
    "dashboard.tasks.label": "Assigned Work",
    "dashboard.tasks.title": "My tasks",
    "dashboard.tasks.emptyTitle": "No active tasks",
    "dashboard.tasks.emptyBody": "Assigned tasks will appear here once your team starts routing work to you.",
    "dashboard.tasks.noProject": "Department task",
    "dashboard.task.status.todo": "To do",
    "dashboard.task.status.in_progress": "In progress",
    "dashboard.task.status.review": "In review",
    "dashboard.task.status.done": "Done",
    "dashboard.announcements.label": "Announcements",
    "dashboard.announcements.title": "Recent updates",
    "dashboard.announcements.emptyTitle": "No announcements yet",
    "dashboard.announcements.emptyBody": "Team and club updates will appear here as soon as leaders publish them.",
    "dashboard.announcements.pinned": "Pinned",
    "dashboard.profile.label": "Profile",
    "dashboard.profile.title": "Keep your member profile current",
    "dashboard.profile.desc": "Update your bio, links, major, and contact details so leaders can route projects and opportunities more accurately.",
    "dashboard.profile.cta": "Open profile",

    // ── Projects ─────────────────────────────────────────────────────────────
    "projects.hero.label": "Projects",
    "projects.hero.title": "Built by",
    "projects.hero.accent": "Engineers",
    "projects.hero.desc": "A live archive of the systems, events, and competitions that define how DRC builds in public.",
    "projects.section.projects.label": "Project Archive",
    "projects.section.projects.title": "Projects",
    "projects.section.projects.desc": "Core systems, prototypes, and technical builds from across the club.",
    "projects.section.events.label": "Event Archive",
    "projects.section.events.title": "Events",
    "projects.section.events.desc": "Workshops, technical sessions, and public club moments collected in one timeline.",
    "projects.section.competitions.label": "Competition Archive",
    "projects.section.competitions.title": "Competitions",
    "projects.section.competitions.desc": "The entries, showcases, and challenge days where DRC competes in public.",
    "projects.section.empty": "Nothing published in this section yet.",
    "projects.state.upcoming": "Upcoming",
    "projects.state.live": "Live",
    "projects.state.completed": "Completed",
    "projects.card.open": "Open archive page",
    "projects.detail.back": "Back to Archive",
    "projects.detail.about": "Archive Details",
    "projects.detail.gallery": "Gallery",
    "projects.detail.stack": "Tech Stack",
    "projects.detail.members": "Members",
    "projects.detail.noMembers": "No public member profiles are attached to this item yet.",
    "projects.detail.github": "Open repository",
    "projects.detail.meta.category": "Category",
    "projects.detail.meta.date": "Date",
    "projects.detail.meta.location": "Location",
    "projects.detail.meta.type": "Type",
    "projects.stats.total": "Total Projects",
    "projects.stats.active": "Active This Year",
    "projects.stats.competitions": "Competition Entries",
    "projects.stats.papers": "Research Papers",
    "projects.portfolio.label": "Portfolio",
    "projects.portfolio.title": "Our Work",
    "projects.portfolio.desc": "Drones, robots, and the software that makes them intelligent.",
    "projects.tech.label": "Tech Stack",
    "projects.tech.title": "Tools of the Trade",
    "projects.tech.desc": "The technologies and platforms powering our builds.",
    "projects.modal.stack": "Tech Stack",
    "projects.modal.link": "View on GitHub",
    "projects.modal.team": "Team",
    "projects.modal.empty": "No team members listed for this project.",
    "projects.card.view": "Click to view details & team →",
    "projects.badge.featured": "Featured",
    "projects.meta.lead": "Lead",
    "projects.filter.all": "All",
    "projects.filter.drones": "Drones",
    "projects.filter.robotics": "Robotics",
    "projects.filter.ai": "AI & Software",
    "projects.filter.research": "Research",
    "projects.anchor.label": "Jump To",
    "projects.anchor.overview": "Overview",
    "projects.anchor.portfolio": "Project Grid",
    "projects.anchor.stack": "Tech Stack",
    "projects.focus.label": "Build Focus",
    "projects.focus.title": "Projects here feel engineered, not decorative.",
    "projects.focus.desc": "This page is structured like a working studio: systems, software, and research grouped by what they produce and how they are built.",
    "projects.focus.systems.title": "Systems builds",
    "projects.focus.systems.desc": "Autonomous flight, robotics, and embedded work built around testing loops, constraints, and field performance.",
    "projects.focus.software.title": "Software layers",
    "projects.focus.software.desc": "Interfaces, control tools, and AI-backed workflows that support real devices, members, and operations.",
    "projects.focus.research.title": "Research tracks",
    "projects.focus.research.desc": "Experiments, papers, and validation work that turn prototypes into documented learning.",
    "projects.empty.title": "No projects match this filter",
    "projects.empty.body": "Try another category or return to the full portfolio to see the wider technical spread.",
    "projects.apply.label": "Members",
    "projects.apply.title": "Open project roles",
    "projects.apply.desc": "Signed-in members can apply to join this project in one of the roles below.",
    "projects.apply.roles": "roles",
    "projects.apply.applied": "Applied",
    "projects.apply.allApplied": "You already applied for every open role on this project.",
    "projects.apply.note": "Why are you a fit?",
    "projects.apply.notePlaceholder": "Share the experience, availability, or motivation that makes you a strong fit for this role.",
    "projects.apply.cta": "Apply",
    "projects.apply.submitting": "Submitting…",
    "projects.apply.success": "Application submitted. The project lead can review it from the member side.",
    "projects.apply.error": "Could not submit your application. Please try again.",
    "project.status.testing": "Testing",
    "project.status.archived": "Archived",

    // ── Workshops ────────────────────────────────────────────────────────────
    "workshops.hero.label": "Workshops",
    "workshops.hero.title": "Learn · Build ·",
    "workshops.hero.accent": "Innovate",
    "workshops.hero.desc": "Live sessions and recorded workshops covering drones, robotics, AI, fabrication, and software.",
    "workshops.live.title": "Live & Upcoming",
    "workshops.live.sessions": "sessions",
    "workshops.live.past": "Past Live Sessions",
    "workshops.library.label": "Recordings",
    "workshops.library.title": "Workshop Library",
    "workshops.library.desc": "Browse past sessions — available anytime at your own pace.",
    "workshops.badge.completed": "Completed",
    "workshops.badge.upcoming": "Upcoming",
    "workshops.badge.open": "Registration Open",
    "workshops.badge.closed": "Registration Closed",
    "workshops.badge.full": "Fully Booked",
    "workshops.live.by": "by",
    "workshops.live.registered": "registered",
    "workshops.live.cta": "Register Now →",
    "workshops.live.fullnote": "This session is full. Check back for future workshops.",
    "workshops.modal.success.title": "You're registered!",
    "workshops.modal.success.desc": "We'll see you at",
    "workshops.modal.success.done": "Done",
    "workshops.modal.error": "Registration failed. Please try again.",
    "workshops.modal.live": "LIVE WORKSHOP",
    "workshops.modal.fullName": "Full Name *",
    "workshops.modal.fullName.placeholder": "Your full name",
    "workshops.modal.email": "Email *",
    "workshops.modal.email.placeholder": "your@email.com",
    "workshops.modal.universityId": "University ID",
    "workshops.modal.phone": "Phone",
    "workshops.modal.optional": "Optional",
    "workshops.modal.department": "Department / Major",
    "workshops.modal.department.placeholder": "e.g. Computer Science, Electrical Engineering",
    "workshops.modal.notes": "Notes",
    "workshops.modal.notes.placeholder": "Any questions or special requirements? (optional)",
    "workshops.modal.cancel": "Cancel",
    "workshops.modal.registering": "Registering…",
    "workshops.modal.register": "Register →",
    "workshops.anchor.label": "Jump To",
    "workshops.anchor.overview": "Overview",
    "workshops.anchor.live": "Live Sessions",
    "workshops.anchor.library": "Library",
    "workshops.modes.live.title": "Live sessions",
    "workshops.modes.live.desc": "Time-bound sessions for registration, attendance, and direct interaction with mentors or presenters.",
    "workshops.modes.library.title": "Recorded library",
    "workshops.modes.library.desc": "An always-available archive for members who want to revisit skills at their own pace.",
    "workshops.modes.path.title": "Skill paths",
    "workshops.modes.path.desc": "The strongest workshop experience is progressive: learn basics, apply them, then return for deeper sessions.",
    "workshops.empty.live.title": "No live sessions are open right now",
    "workshops.empty.live.body": "Recorded workshops are still available below, and new live sessions will appear here once they are published.",
    "workshops.modal.at": "at",
    "workshops.recorded.empty.title": "No recorded workshops yet.",
    "workshops.recorded.empty.desc": "When Development publishes Google Drive workshop sessions, they will appear here.",
    "workshops.category.default": "Workshop",
    "workshops.presenter.default": "Development",
    "workshops.recorded.default": "Recorded",
    "workshops.sessions.one": "session",
    "workshops.sessions.many": "sessions",
    "workshops.drive.label": "Drive",
    "workshops.sessions.moreDrive": "more in Drive",

    // ── Footer ───────────────────────────────────────────────────────────────
    "footer.brand.name": "DRC",
    "footer.brand.subtitle": "Drones & Robotics Club",
    "footer.brand.description": "Building the next generation of autonomous systems, competitive robotics, and aerial innovation. We engineer the future.",
    "footer.brand.arabic": "نادي الدرونز والروبوت",
    "footer.club.title": "Club",
    "footer.club.about": "About",
    "footer.club.projects": "Projects",
    "footer.club.events": "Events",
    "footer.club.team": "Team",
    "footer.connect.title": "Connect",
    "footer.connect.join": "Join Us",
    "footer.connect.twitter": "Twitter / X",
    "footer.connect.instagram": "Instagram",
    "footer.connect.linkedin": "LinkedIn",
    "footer.connect.tiktok": "TikTok",
    "footer.connect.empty": "Social handles coming soon.",
    "footer.contact.title": "For companies and partners",
    "footer.contact.desc": "Invite DRC for visits, sponsorships, collaborations, demonstrations, and student technical opportunities.",
    "footer.bottom.copyright": "All rights reserved.",
    "footer.bottom.status": "Accepting Members",

    // ── Login ─────────────────────────────────────────────────────────────────
    "login.title": "Welcome Back",
    "login.subtitle": "Sign in to your DRC member portal",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Sign In",
    "login.forgot": "Forgot password?",
    "login.show_password": "Show password",
    "login.hide_password": "Hide password",
    "login.back": "← Back to website",
    "login.or": "OR",
    "login.demo.show": "Quick login with demo account",
    "login.demo.hide": "Hide demo accounts",
    "login.error.device": "New device detected. Check your email for a confirmation link.",
    "login.error.invalid": "Invalid credentials.",
    "login.info.setup": "Welcome! Check your email for a link to set up your password. The link works for 24 hours.",
  },

  ar: {
    // ── Navigation ────────────────────────────────────────────────────────────
    "nav.about": "عن النادي",
    "nav.projects": "المشاريع",
    "nav.workshops": "ورش العمل",
    "nav.events": "الفعاليات",
    "nav.team": "الفريق",
    "nav.alumni": "الخرّيجون",
    "nav.signin": "تسجيل الدخول",
    "nav.joinus": "انضم إلينا",
    "nav.dashboard": "لوحة التحكم",

    // ── Home ─────────────────────────────────────────────────────────────────
    "home.hero.kicker": "روبوتات يبنيها الطلاب. ودليل يراه الجميع.",
    "home.status": "في انطلاق",
    "home.hero1": "نبتكر",
    "home.hero2": "لنحلّق.",
    "home.sub": "نادٍ طلابي بجامعة الملك سعود يهدف إلى تمكين الابتكار وتعزيز المهارات التقنية للطلاب والطالبات في مجالات الدرونز والروبوتات، تماشيًا مع رؤية المملكة 2030.",
    "home.tagline": "Drones & Robotics Club — King Saud University",
    "home.cta.join": "انضم إلى DRC",
    "home.cta.projects": "استكشف المشاريع",
    "home.cta.workshops": "تصفّح ورش العمل",
    "home.cta.partner": "تواصل الشركاء",
    "home.cta1": "انضم الآن",
    "home.cta2": "شاهد أعمالنا ←",
    "home.proof.systems": "الأنظمة التقنية",
    "home.proof.output": "المخرجات الظاهرة",
    "home.proof.output.value": "مشاريع وورش وعروض",
    "home.proof.partner": "تواصل الشركات",
    "home.paths.label": "ابدأ من هنا",
    "home.paths.title": "اختر الطريق المناسب للدخول.",
    "home.paths.desc": "لكل زائر هدف مختلف. هذه أسرع الطرق للدخول إلى تجربة DRC.",
    "home.paths.join.label": "للمهتمين بالانضمام",
    "home.paths.join.title": "انضم إلى النادي",
    "home.paths.join.desc": "قدّم، واختر لجنتك، وابدأ البناء مع الفريق.",
    "home.paths.join.cta": "قدّم خلال دقائق",
    "home.paths.projects.label": "للزوار",
    "home.paths.projects.title": "استكشف المشاريع",
    "home.paths.projects.desc": "شاهد الأنظمة والنماذج والبرمجيات التي يعمل عليها الأعضاء الآن.",
    "home.paths.projects.cta": "شاهد الأعمال الحالية",
    "home.paths.workshops.label": "للمهتمين بالتعلّم",
    "home.paths.workshops.title": "تصفّح ورش العمل",
    "home.paths.workshops.desc": "شاهد التسجيلات أو سجّل في الجلسات المباشرة وطوّر مهاراتك بسرعة.",
    "home.paths.workshops.cta": "ابدأ التعلّم",
    "home.announcements.label": "الإعلانات",
    "home.announcements.title": "ما الذي يحتاج الزائر إلى ملاحظته الآن",
    "home.announcements.desc": "تحديثات مثبتة وإعلانات مهمة وسياق سريع للزوار الذين يريدون معرفة آخر ما يحدث في النادي.",
    "home.mediawall.label": "الجدار الإعلامي",
    "home.mediawall.title": "دليل بصري على أن النادي في حالة حركة",
    "home.mediawall.desc": "جدار واحد يجمع الريلز وصور المشاريع وتغطية الفعاليات ومرئيات الإعلانات حتى يفهم الزائر نبض النادي بسرعة.",
    "home.mediawall.emptyTitle": "الجدار الإعلامي ينتظر مواد جديدة",
    "home.mediawall.emptyBody": "بمجرد نشر صور عامة جديدة أو ريلز أو تغطية فعاليات أو مرئيات إعلانات ستظهر هنا مباشرة.",
    "home.mediawall.cta": "افتح الصفحة المرتبطة",
    "home.mediawall.badge.reel": "ريل",
    "home.mediawall.badge.photo": "صورة",
    "home.mediawall.badge.video": "فيديو",
    "home.mediawall.badge.post": "منشور",
    "home.mediawall.badge.project": "مشروع",
    "home.mediawall.badge.event": "فعالية",
    "home.mediawall.badge.announcement": "إعلان",
    "home.signal.event": "الفعالية التالية",
    "home.signal.event.empty": "لا توجد فعالية بعد",
    "home.signal.event.detail": "ستظهر هنا الفعالية القادمة بمجرد نشرها.",
    "home.signal.media": "التغطية الإعلامية",
    "home.signal.media.empty": "هادئ",
    "home.signal.media.detail": "هناك تحديثات بصرية حديثة منشورة على الواجهة.",
    "home.signal.media.detailEmpty": "لا توجد مادة بصرية منشورة حاليًا.",
    "home.signal.join": "استقبال الأعضاء",
    "home.signal.join.open": "مفتوح",
    "home.signal.join.closed": "متوقف",
    "home.signal.join.detailOpen": "يتم استقبال الطلبات في الوقت الحالي.",
    "home.signal.join.detailClosed": "نافذة الانضمام القادمة لم تُفتح بعد.",
    "home.pulse.label": "نبض النادي",
    "home.pulse.title": "ما الذي يتحرك هذا الأسبوع عبر اللجان",
    "home.pulse.desc": "قراءة خفيفة توضح الفرق النشطة وأين تتركز الحركة وما الذي يظهر حاليًا على الواجهة العامة.",
    "home.pulse.thisWeek": "هذا الأسبوع",
    "home.pulse.state.high": "مرتفع",
    "home.pulse.state.medium": "متابعة",
    "home.pulse.state.quiet": "هادئ",
    "home.motm.label": "نجم الشهر",
    "home.motm.title": "أعضاء الشهر",
    "home.motm.desc": "مُكرَّمون هذا الشهر على مساهماتهم المتميزة.",
    "home.motm.viewteam": "عرض الفريق كامل ←",
    "home.admin.manage": "إدارة ←",
    "admin.manage": "إدارة ←",
    "stats.projects": "مشروع منجز",
    "stats.competitions": "منافسة فزنا بها",
    "stats.members": "عضو نشط",
    "stats.departments": "لجان",
    "section.story.label": "الواجهة الرئيسية",
    "section.story.title": "نادٍ يبدو حيًا لأن العمل فيه مرئي.",
    "section.story.desc": "تمنح الكتل المميزة فرق الإعلام والقيادة طريقة لعرض ما يبنيه الأعضاء ويتعلمونه وينشرونه بدون تعديل الكود.",
    "section.whatwedo.label": "ماذا نفعل",
    "section.whatwedo.title": "أكثر من مجرد نادي",
    "section.whatwedo.desc": "نحن مجتمع من البنائين والمبرمجين والمبدعين والمنظمين نحوّل الأفكار الطموحة إلى واقع معًا.",
    "section.workshops.label": "التعلم",
    "section.workshops.title": "تسجيلات ورش العمل",
    "section.workshops.desc": "فاتتك جلسة؟ شاهد جميع ورش عملنا المسجلة — من تجميع الطائرات إلى الذكاء الاصطناعي وأكثر.",
    "section.workshops.viewall": "عرض الكل ←",
    "section.projects.label": "مميز",
    "section.projects.title": "أحدث المشاريع",
    "section.projects.desc": "لمحة عن ما تبنيه فرقنا الآن.",
    "section.projects.viewall": "عرض الكل ←",
    "section.cta.title": "هل أنت مستعد لبناء المستقبل؟",
    "section.cta.desc1": "اهندس وبرمج ونافس مع الفرق التقنية.",
    "section.cta.desc2": "اروِ قصتنا وأدِر فعالياتنا وكبّر مجتمعنا.",
    "section.cta.apply": "قدّم الآن",
    "section.cta.learn": "اعرف المزيد ←",
    "project.status.completed": "مكتمل",
    "project.status.inprogress": "قيد التنفيذ",
    "project.status.planned": "مخطط",
    "workshop.watch": "شاهد التسجيل",
    "workshop.duration": "دقيقة",
    "highlight.innovation.title": "الابتكار",
    "highlight.innovation.desc": "الطائرات والروبوتات والبحث والتطوير — حيث يحوّل أعضاؤنا الأفكار إلى نماذج أولية يتنافسون بها محليًا ودوليًا.",
    "highlight.development.title": "التطوير",
    "highlight.development.desc": "برمجيات وتطبيقات ومنصات — الشيفرة التي تشغّل أنظمتنا المستقلة والأدوات التي يبنيها أعضاؤنا.",
    "highlight.community.title": "المجتمع",
    "highlight.community.desc": "الإعلام والعلاقات العامة والموارد البشرية واللوجستيات ومدارات — الجانب الإنساني الذي يجعل كل شيء آخر ممكنًا.",
    "scroll": "تمرير",

    // ── About ─────────────────────────────────────────────────────────────────
    "about.hero.label": "عن النادي",
    "about.hero.title": "من DAAS إلى DRC —",
    "about.hero.accent": "أربع سنوات في السماء",
    "about.hero.desc": "تأسس النادي عام 2022 باسم DAAS (Drones & Autonomous Systems)، وأصبح اليوم أحد أكبر المجتمعات الهندسية الطلابية في جامعة الملك سعود — تسع لجان تعمل كوحدة واحدة في البناء والتدريب والمنافسة.",
    "about.vision.title": "رؤيتنا",
    "about.vision.body": "أن نكون المجتمع الطلابي الرائد للدرونز والأنظمة الذاتية في المملكة — نطوّر بنّائين ومتواصلين وقادة يحملون رؤية 2030 من خلال عمل هندسي حقيقي.",
    "about.vision.tagline": "Saudi Arabia's leading student community for drones and autonomous systems",
    "about.mission.title": "مهمتنا",
    "about.mission.body": "تمكين كل عضو — مهندسًا كان أو مصممًا أو معدّ محتوى أو منظّمًا — بمهارات حقيقية وتجارب عملية ومجتمع يحوّل الطموح إلى تحليق.",
    "about.mission.tagline": "Empowering innovation, aligned with Saudi Vision 2030",
    "about.values.label": "قيمنا",
    "about.values.title": "ما يحركنا",
    "about.values.innovation.title": "الابتكار أولاً",
    "about.values.innovation.desc": "لا نتبع القوالب. كل مشروع وفعالية وفكرة هي فرصة للتجاوز المتوقع وبناء شيء أفضل.",
    "about.values.community.title": "مجتمعنا قوتنا",
    "about.values.community.desc": "المعرفة تنمو حين تُشارَك. ثقافتنا في الإرشاد والتعاون تحوّل المبتدئين إلى بنّائين والبنّائين إلى قادة.",
    "about.values.competition.title": "مستعدون للتنافس",
    "about.values.competition.desc": "نتدرّب للفوز. من هاكاثونات محلية إلى بطولات روبوتية دولية، نقدّم أفضل ما لدينا في كل مرة.",
    "about.depts.label": "الهيكل",
    "about.depts.title": "لجاننا",
    "about.depts.desc": "تسع لجان متخصصة تعمل معًا لتحقيق الابتكار على كل المستويات.",
    "dept.executive.name": "الهيئة التنفيذية",
    "dept.executive.desc": "قيادة النادي واستراتيجيته والتنسيق بين اللجان",
    "dept.hr.name": "الموارد البشرية",
    "dept.hr.desc": "التجنيد والتأهيل وتطوير الأعضاء",
    "dept.development.name": "التطوير",
    "dept.development.desc": "برمجيات وتطبيقات ومنصات وأنظمة ذكاء اصطناعي",
    "dept.innovation.name": "الابتكار",
    "dept.innovation.desc": "طائرات وروبوتات وبحث وتطوير وهندسة تنافسية",
    "dept.media.name": "الإعلام",
    "dept.media.desc": "إنتاج المحتوى والتصوير والهوية البصرية",
    "dept.pr.name": "العلاقات العامة",
    "dept.pr.desc": "الشراكات الخارجية والرعايات والتواصل",
    "dept.finance.name": "المالية",
    "dept.finance.desc": "الميزانيات والتمويل والتخطيط المالي",
    "dept.logistics.name": "اللوجستية",
    "dept.logistics.desc": "الفعاليات وإدارة المعدات والعمليات",
    "dept.madarat.name": "مدارات",
    "dept.madarat.desc": "تطوير مهارات الأعضاء وورش العمل والمبادرات التعليمية",
    "about.timeline.label": "مسيرتنا",
    "about.timeline.title": "نمو عام بعد عام",
    "about.timeline.2020.event": "تأسيس النادي",
    "about.timeline.2020.detail": "بدأنا كمجموعة صغيرة من عشاق الطائرات والروبوتات بـ 15 عضوًا مؤسسًا",
    "about.timeline.2021.event": "أول مشاركة تنافسية",
    "about.timeline.2021.detail": "شاركنا في أول تحدٍّ وطني للروبوتات وحققنا مركزًا ضمن أفضل خمسة",
    "about.timeline.2022.event": "إعادة هيكلة اللجان",
    "about.timeline.2022.detail": "نظّمنا عملنا في لجان متخصصة لتوسيع أثرنا وخدمة مزيد من الأعضاء",
    "about.timeline.2023.event": "الانطلاق الدولي",
    "about.timeline.2023.detail": "تنافسنا في دوريات الطائرات والروبوتات الإقليمية لأول مرة",
    "about.timeline.2024.event": "أسرع نادٍ نموًا في الحرم الجامعي",
    "about.timeline.2024.detail": "وصلنا إلى أكثر من 77 عضوًا نشطًا في تسع لجان",
    "about.timeline.2025.event": "شراكات بحثية وصناعية",
    "about.timeline.2025.detail": "نتعاون مع جهات خارجية في مشاريع أنظمة مستقلة واقعية",

    // ── Team ──────────────────────────────────────────────────────────────────
    "team.hero.label": "الفريق",
    "team.hero.title": "الأشخاص وراء",
    "team.hero.accent": "النادي",
    "team.hero.desc": "تعرّف على البنائين والمبدعين والمنظمين والقادة الذين يُحرّكون DRC عبر تسع لجان.",
    "team.stats.members": "عضو نشط",
    "team.stats.departments": "لجان",
    "team.stats.officers": "مسؤول",
    "team.executive.label": "تنفيذي",
    "team.executive.title": "قيادة النادي",
    "team.executive.desc": "الرئيس ونواب الرئيس ومشرف المشاريع الذين يقودون رؤية DRC وعملياتها.",
    "team.depts.label": "اللجان",
    "team.depts.title": "قيادة اللجان",
    "team.depts.desc": "كل لجنة يقودها رئيس ونائب رئيس يعملان جنبًا إلى جنب.",
    "team.qa.title": "ضمان الجودة",
    "team.qa.desc": "ثلاثة قادة لضمان الجودة ضمن لجنة الابتكار للحفاظ على المعايير في جميع المشاريع.",
    "team.role.president": "رئيس النادي",
    "team.role.vp": "نائب الرئيس",
    "team.role.supervisor": "مشرف المشاريع",
    "team.role.leader": "رئيس اللجنة",
    "team.role.vice": "نائب رئيس اللجنة",
    "team.role.co_leader": "قائد مشارك",
    "team.role.qa_leader": "قائد ضمان الجودة",
    "team.role.sub_leader": "قائد فرعي",
    "team.placeholder.name": "—",
    "team.motm.label": "تقدير",
    "team.motm.title": "أعضاء الشهر",
    "team.motm.desc": "أعضاء متميزون يُكرَّمون كل شهر على مساهماتهم في النادي.",
    "team.motm.empty": "يتم اختيار الأعضاء كل شهر من قِبل الفريق القيادي.",
    "team.motm.emptyTitle": "سيظهر التقدير هنا",
    "team.join.title": "كن جزءًا من الفريق",
    "team.join.desc": "سواء كنت تبني أو تبرمج أو تبدع أو تنظّم — هناك لجنة تناسبك.",
    "team.join.cta": "قدّم الآن ←",
    "team.alumni.label": "الخرّيجون",
    "team.alumni.title": "خرّيجونا",
    "team.alumni.desc": "أعضاء تخرّجوا وانطلقوا — جزء دائم من حكاية DRC.",
    "team.alumni.empty": "ملفات الخرّيجين قريبًا.",
    "team.alumni.emptyTitle": "ملفات الخرّيجين غير منشورة بعد",
    "team.anchor.label": "انتقل إلى",
    "team.anchor.departments": "اللجان",
    "team.anchor.directory": "الدليل",
    "team.anchor.recognition": "التقدير",
    "team.anchor.alumni": "الخرّيجون",
    "team.deptmoments.label": "ملامح اللجان",
    "team.deptmoments.title": "لكل لجنة إيقاعها الخاص",
    "team.deptmoments.desc": "كل فريق يحمل مسؤوليات مختلفة. هذا يمنح الزائر فهمًا أسرع لطريقة عمل النادي فعليًا.",
    "team.deptmoments.need": "الاحتياج الحالي",
    "team.dept.need.hr": "تنسيق الاستقطاب ورعاية الأعضاء والمتابعة الموثوقة لمرحلة الانضمام.",
    "team.dept.need.development": "بنّاؤون بعقلية منتج قادرون على شحن الأدوات ولوحات التحكم والتكاملات.",
    "team.dept.need.innovation": "صنّاع نماذج أولية قادرون على تكرار التجريب في العتاد والتحكم ودورات الاختبار.",
    "team.dept.need.media": "مصوّرون ومحررون ورواة قصة قادرون على جعل العمل مرئيًا.",
    "team.dept.need.pr": "مشغّلون يعززون الشراكات والتواصل والترويج للفعاليات.",
    "team.dept.need.finance": "ميزانيات واضحة وتتبع للرعايات وسير شراء منضبط.",
    "team.dept.need.logistics": "مخططون جاهزون للفعاليات قادرون على إدارة المعدات والتجهيز والعمليات بهدوء.",
    "team.dept.need.madarat": "مصممو تعلم قادرون على تحويل معرفة النادي إلى تدريب قابل للتكرار.",

    // ── Join ──────────────────────────────────────────────────────────────────
    "join.hero.label": "العضوية",
    "join.hero.title": "كن جزءًا من",
    "join.hero.accent": "مجتمع المبدعين",
    "join.hero.desc": "إذا كان شغفك في الدرونز والروبوتات والأنظمة الذاتية — هذا مكانك. سجّل، اختر لجنتك، وابدأ البناء.",
    "join.closed.badge": "مغلق",
    "join.benefits.label": "المميزات",
    "join.benefits.title": "لماذا تنضم إلى DRC؟",
    "join.benefits.desc": "أكثر من سطر في سيرتك الذاتية — تجربة تُشكّل مسيرتك ومجتمعك.",
    "join.benefit.experience.title": "تجربة عملية حقيقية",
    "join.benefit.experience.desc": "ابنِ مشاريع فعلية — طائرات وروبوتات وبرمجيات وفعاليات ومبادرات مجتمعية — لا مجرد نظرية.",
    "join.benefit.compete.title": "نافِس وتفوّق",
    "join.benefit.compete.desc": "مثّل جامعتك في المنافسات الوطنية والإقليمية في مجالات الهندسة والابتكار.",
    "join.benefit.community.title": "مجتمع وإرشاد",
    "join.benefit.community.desc": "تعلّم من الأعضاء ذوي الخبرة وتعاون مع أقران متحمسين من مختلف التخصصات.",
    "join.benefit.workshops.title": "ورش عمل وتدريب",
    "join.benefit.workshops.desc": "جلسات منتظمة في الإلكترونيات والبرمجة والتصميم والإعلام وأكثر.",
    "join.benefit.career.title": "فرص مهنية",
    "join.benefit.career.desc": "ابنِ ملفك المهني ووسّع شبكة علاقاتك وتواصل مع رعاة الصناعة.",
    "join.benefit.equipment.title": "الوصول إلى الموارد",
    "join.benefit.equipment.desc": "استخدم مختبرنا وأدواتنا وطابعات ثلاثية الأبعاد ومحاكيات الطيران ومرافق الاختبار.",
    "join.process.label": "الخطوات",
    "join.process.title": "كيف تنضم",
    "join.process.desc": "أربع خطوات بسيطة لتصبح عضوًا في DRC.",
    "join.step1.title": "أكمل الطلب",
    "join.step1.desc": "أدخل معلوماتك واهتماماتك واللجنة التي تفضّلها في النموذج أدناه.",
    "join.step2.title": "احضر التوجيه",
    "join.step2.desc": "انضم إلى إحدى جلسات التوجيه لتلتقي بالفريق وترى مساحة عملنا.",
    "join.step3.title": "انضم إلى لجنة",
    "join.step3.desc": "يتم توجيهك إلى لجنة مناسبة بناءً على مهاراتك واهتماماتك.",
    "join.step4.title": "ابدأ المساهمة",
    "join.step4.desc": "انغمس في المشاريع وحضور ورش العمل وابدأ رحلتك مع DRC.",
    "join.form.label": "التقديم",
    "join.form.title": "نموذج التقديم",
    "join.form.desc": "أكمل النموذج وسنتواصل معك. تُراجَع الطلبات باستمرار.",
    "join.form.name": "الاسم الكامل",
    "join.form.name.placeholder": "اسمك الكامل",
    "join.form.id": "الرقم الجامعي",
    "join.form.id.placeholder": "مثال: 44XXXXXXX",
    "join.form.email": "البريد الإلكتروني",
    "join.form.email.placeholder": "بريدك@example.com",
    "join.form.phone": "رقم الجوال",
    "join.form.phone.placeholder": "مثال: 05XXXXXXXX",
    "join.form.major": "التخصص / مجال الدراسة",
    "join.form.major.placeholder": "مثال: هندسة الحاسب",
    "join.form.dept": "اللجنة المفضّلة",
    "join.form.dept.placeholder": "اختر لجنة",
    "join.form.motivation": "لماذا تريد الانضمام إلى DRC؟",
    "join.form.motivation.placeholder": "أخبرنا عن اهتماماتك وخبراتك وما تأمل في المساهمة به...",
    "join.form.skills": "المهارات ذات الصلة",
    "join.form.skills.optional": "(اختياري)",
    "join.form.skills.placeholder": "مثال: Python، أردوينو، CAD، مونتاج فيديو، تنظيم فعاليات",
    "join.form.submit": "إرسال الطلب",
    "join.form.submitting": "جارٍ الإرسال…",
    "join.form.consent": "بالإرسال، توافق على التواصل معك من قِبل DRC بشأن طلبك.",
    "join.readiness.label": "قبل الإرسال",
    "join.readiness.title": "جاهزية الطلب",
    "join.readiness.desc": "الطلب القوي يمنح الفريق سياقًا كافيًا لوضعك في البداية المناسبة.",
    "join.readiness.progress": "تقدّم النموذج",
    "join.readiness.identity": "تم إدخال الاسم ووسائل التواصل",
    "join.readiness.dept": "تم اختيار اللجنة التي تريد أن تبدأ فيها",
    "join.readiness.context": "أضفت سياقًا أكاديميًا مثل التخصص أو الرقم الجامعي",
    "join.readiness.motivation": "شرحك يوضّح ما تريد تعلّمه أو المساهمة به",
    "join.readiness.skills": "أضفت مهارات أو اهتمامات يستطيع الفريق البناء عليها",
    "join.readiness.selected": "اللجنة المختارة",
    "join.readiness.selected.empty": "اختر لجنة لتخصيص طلبك بشكل أفضل.",
    "join.readiness.selected.hint": "لا يزال بإمكانك التعاون مع لجان أخرى لاحقًا.",
    "join.expectations.label": "بعد الإرسال",
    "join.expectations.title": "ماذا يحدث بعد ذلك",
    "join.expectations.desc": "يدخل طلبك إلى قائمة مراجعة الموارد البشرية ثم ينتقل إلى الفريق الأنسب.",
    "join.expectations.step1.title": "تم استلام الطلب",
    "join.expectations.step1.desc": "يتم حفظ بياناتك فورًا ووضع الطلب في حالة انتظار.",
    "join.expectations.step2.title": "قائمة مراجعة الموارد البشرية",
    "join.expectations.step2.desc": "يراجع فريق الموارد البشرية الخلفية والدافع واللجنة المفضلة.",
    "join.expectations.step3.title": "تحديد أفضل مواءمة",
    "join.expectations.step3.desc": "يستخدم القادة اهتماماتك ومهاراتك لتوجيهك إلى أفضل نقطة بداية.",
    "join.expectations.step4.title": "التواصل بالخطوة التالية",
    "join.expectations.step4.desc": "يتم التواصل مع المرشحين بالخطوة التالية مثل التوجيه أو تفاصيل الانضمام.",
    "join.success.title": "تم استلام طلبك!",
    "join.success.desc": "شكرًا لتقديمك إلى DRC. سنراجع طلبك ونتواصل معك قريبًا.",
    "join.success.reference": "المرجع",
    "join.success.next": "ماذا يحدث بعد ذلك",
    "join.success.timelineIntro": "طلبك الآن داخل مسار المراجعة.",
    "join.success.keep": "احتفظ بهذا المرجع إذا احتجت إلى المتابعة مع الفريق.",
    "join.success.cta": "العودة إلى الرئيسية",
    "join.error.generic": "حدث خطأ ما. يرجى المحاولة مجددًا.",
    "join.faq.label": "الأسئلة الشائعة",
    "join.faq.title": "أسئلة شائعة",
    "join.faq.q1": "هل أحتاج إلى خبرة مسبقة؟",
    "join.faq.a1": "لا على الإطلاق! نرحّب بالمبتدئين تمامًا. برنامج ورش العمل مصمم ليأخذك من الصفر، وكل لجنة فيها أعضاء خبراء مستعدون للمساعدة.",
    "join.faq.q2": "ما مقدار الوقت المطلوب؟",
    "join.faq.a2": "يقضي معظم الأعضاء 4–6 ساعات أسبوعيًا في أنشطة النادي — اجتماعات وورش عمل وعمل في المشاريع. قد تتطلب مواسم المنافسات وقتًا أكثر.",
    "join.faq.q3": "ما اللجان المتاحة للانضمام؟",
    "join.faq.a3": "لدينا سبع لجان مفتوحة للأعضاء العامين: الابتكار والهندسة، والتطوير، والإعلام، والعلاقات العامة، والموارد البشرية، والمالية، واللوجستية. يمكنك التعبير عن تفضيلك في الطلب.",
    "join.faq.q4": "هل هناك رسوم عضوية؟",
    "join.faq.a4": "الانضمام إلى DRC مجاني تمامًا. بعض ورش العمل المتخصصة أو السفر للمنافسات قد يرتبط بتكاليف، كثيرًا ما تغطيها رعايتنا.",
    "join.faq.q5": "هل يمكنني الانتماء لأكثر من لجنة؟",
    "join.faq.a5": "ستُسنَد إلى لجنة رئيسية واحدة، لكن التعاون بين اللجان شائع ومشجَّع في معظم المشاريع.",

    // ── Events ───────────────────────────────────────────────────────────────
    "events.hero.label": "الفعاليات",
    "events.hero.title": "نافِس. تعلّم.",
    "events.hero.accent": "ابنِ معًا.",
    "events.hero.desc": "من سباقات الطائرات عالية المخاطر إلى ورش عمل تطبيقية — فعالياتنا هي حيث تُصقَل المهارات وتُصنَع الأساطير.",
    "events.upcoming.label": "قادم",
    "events.upcoming.title": "ما القادم",
    "events.upcoming.desc": "ضَع علامة على تقويمك. هذه فعاليات لا تُفوَّت.",
    "events.upcoming.empty": "لا توجد فعاليات قادمة حاليًا. تحقّق قريبًا.",
    "events.upcoming.seats": "مقاعد متبقية",
    "events.upcoming.seats_full": "اكتمل العدد",
    "events.hours.label": "ساعات تطوعية",
    "events.hours.available": "متاحة للأعضاء بعد انتهاء الفعالية",
    "events.hours.confirm": "تأكيد الحضور",
    "events.hours.pending": "تم تأكيد الحضور وبانتظار اعتماد الموارد البشرية",
    "events.hours.approved": "تم اعتماد الحضور",
    "events.hours.rejected": "تم رفض تأكيد الحضور",
    "events.hours.locked": "يفتح تأكيد الحضور بعد نهاية الفعالية",
    "events.hours.success": "تم إرسال تأكيد الحضور لاعتماد الموارد البشرية.",
    "events.hours.error": "تعذر تأكيد الحضور. حاول مرة أخرى.",
    "events.hours.submitting": "جارٍ الإرسال…",
    "events.achievements.label": "سجلّنا",
    "events.achievements.title": "حضور مُثبَت",
    "events.achievements.desc": "تاريخنا التنافسي يتحدث عن نفسه — أبرز محطات رحلتنا حتى الآن.",
    "events.recent.label": "ملخّص",
    "events.recent.title": "فعاليات سابقة",
    "events.recent.desc": "نظرة على آخر لقاءاتنا وورشنا ومنافساتنا.",
    "events.recent.empty": "لا توجد فعاليات سابقة لعرضها بعد.",
    "events.type.competition": "منافسة",
    "events.type.workshop": "ورشة",
    "events.type.meetup": "لقاء",
    "events.type.general": "فعالية",
    "events.cta.workshops": "استعرض جميع ورش العمل ←",

    // ── Dashboard ────────────────────────────────────────────────────────────
    "dashboard.overview.title": "مرحبًا بعودتك",
    "dashboard.overview.member": "عضو",
    "dashboard.overview.desc": "عرض مباشر لما يهم اليوم عبر العمل والساعات والفعاليات والإعلانات.",
    "dashboard.overview.partial": "تعذر تحميل بعض بيانات لوحة التحكم المباشرة. يتم عرض ما هو متاح حاليًا.",
    "dashboard.stats.members": "الأعضاء النشطون",
    "dashboard.stats.projects": "المشاريع النشطة",
    "dashboard.stats.events": "الفعاليات القادمة",
    "dashboard.stats.departments": "اللجان",
    "dashboard.today.label": "مشهد اليوم",
    "dashboard.today.title": "ما يستحق الانتباه أولًا",
    "dashboard.today.desc": "مكان واحد لفعاليتك التالية ومهامك المفتوحة وساعاتك الحالية وما يحتاج متابعة.",
    "dashboard.nextEvent.label": "الفعالية التالية",
    "dashboard.nextEvent.emptyTitle": "لا توجد فعالية قادمة بعد",
    "dashboard.nextEvent.emptyBody": "عند نشر فعالية جديدة للنادي ستظهر هنا مع الوقت والموقع والتفاصيل الأساسية.",
    "dashboard.nextEvent.fallback": "ستظهر تفاصيل الفعالية هنا بمجرد أن يضيف المنظمون الوصف الكامل.",
    "dashboard.nextEvent.cta": "افتح الفعاليات",
    "dashboard.hours.label": "الساعات التطوعية",
    "dashboard.hours.approved": "المدخلات المعتمدة",
    "dashboard.hours.pending": "بانتظار المراجعة",
    "dashboard.quickLinks.label": "روابط سريعة",
    "dashboard.quickLinks.department": "افتح مساحة لجنّتي",
    "dashboard.quickLinks.profile": "حدّث ملفي الشخصي",
    "dashboard.actions.label": "قائمة الإجراءات",
    "dashboard.actions.title": "ما يحتاج إجراء",
    "dashboard.actions.tasks.title": "مهام مسندة مفتوحة",
    "dashboard.actions.tasks.body": "لا يزال لديك {count} من المهام النشطة التي تحتاج تحريكًا.",
    "dashboard.actions.hours.title": "ساعات بانتظار الاعتماد",
    "dashboard.actions.hours.body": "يوجد {count} من إدخالات الساعات المسجلة ما زالت بانتظار الموافقة.",
    "dashboard.actions.event.title": "استعد للفعالية التالية",
    "dashboard.actions.clear.title": "أنت منجز حاليًا",
    "dashboard.actions.clear.body": "لا توجد عوائق عاجلة الآن. هذا وقت جيد لاستكشاف المشاريع أو ورش العمل الحالية.",
    "dashboard.tasks.label": "العمل المسند",
    "dashboard.tasks.title": "مهامي",
    "dashboard.tasks.emptyTitle": "لا توجد مهام نشطة",
    "dashboard.tasks.emptyBody": "ستظهر المهام هنا عندما يبدأ فريقك في إسناد العمل إليك.",
    "dashboard.tasks.noProject": "مهمة لجنة",
    "dashboard.task.status.todo": "للإنجاز",
    "dashboard.task.status.in_progress": "قيد التنفيذ",
    "dashboard.task.status.review": "قيد المراجعة",
    "dashboard.task.status.done": "مكتملة",
    "dashboard.announcements.label": "الإعلانات",
    "dashboard.announcements.title": "آخر التحديثات",
    "dashboard.announcements.emptyTitle": "لا توجد إعلانات بعد",
    "dashboard.announcements.emptyBody": "ستظهر تحديثات الفرق والنادي هنا فور نشرها من القادة.",
    "dashboard.announcements.pinned": "مثبّت",
    "dashboard.profile.label": "الملف الشخصي",
    "dashboard.profile.title": "حافظ على ملفك الشخصي محدثًا",
    "dashboard.profile.desc": "حدّث النبذة والروابط والتخصص وبيانات التواصل حتى يتمكن القادة من توجيه المشاريع والفرص لك بدقة أكبر.",
    "dashboard.profile.cta": "افتح الملف الشخصي",

    // ── Projects ─────────────────────────────────────────────────────────────
    "projects.hero.label": "المشاريع",
    "projects.hero.title": "بُنيت بواسطة",
    "projects.hero.accent": "المهندسين",
    "projects.hero.desc": "أرشيف حي للأنظمة والفعاليات والمنافسات التي توضّح كيف يبني النادي أعماله أمام الجمهور.",
    "projects.section.projects.label": "أرشيف المشاريع",
    "projects.section.projects.title": "المشاريع",
    "projects.section.projects.desc": "الأنظمة الأساسية والنماذج والأعمال التقنية التي خرجت من فرق النادي.",
    "projects.section.events.label": "أرشيف الفعاليات",
    "projects.section.events.title": "الفعاليات",
    "projects.section.events.desc": "ورش وجلسات تقنية ومحطات عامة للنادي ضمن تسلسل واحد.",
    "projects.section.competitions.label": "أرشيف المنافسات",
    "projects.section.competitions.title": "المنافسات",
    "projects.section.competitions.desc": "المشاركات والتحديات والعروض التي مثّل فيها DRC نفسه علنًا.",
    "projects.section.empty": "لا يوجد محتوى منشور في هذا القسم بعد.",
    "projects.state.upcoming": "قادم",
    "projects.state.live": "مباشر",
    "projects.state.completed": "مكتمل",
    "projects.card.open": "افتح صفحة الأرشيف",
    "projects.detail.back": "العودة إلى الأرشيف",
    "projects.detail.about": "تفاصيل العنصر",
    "projects.detail.gallery": "المعرض",
    "projects.detail.stack": "التقنيات المستخدمة",
    "projects.detail.members": "الأعضاء",
    "projects.detail.noMembers": "لا توجد ملفات أعضاء عامة مرتبطة بهذا العنصر بعد.",
    "projects.detail.github": "افتح المستودع",
    "projects.detail.meta.category": "التصنيف",
    "projects.detail.meta.date": "التاريخ",
    "projects.detail.meta.location": "الموقع",
    "projects.detail.meta.type": "النوع",
    "projects.stats.total": "إجمالي المشاريع",
    "projects.stats.active": "النشطة هذا العام",
    "projects.stats.competitions": "مشاركات تنافسية",
    "projects.stats.papers": "أوراق بحثية",
    "projects.portfolio.label": "المعرض",
    "projects.portfolio.title": "أعمالنا",
    "projects.portfolio.desc": "درونز وروبوتات وبرمجيات تجعلها أكثر ذكاءً.",
    "projects.tech.label": "التقنيات",
    "projects.tech.title": "أدوات العمل",
    "projects.tech.desc": "التقنيات والمنصات التي تشغل مشاريعنا.",
    "projects.modal.stack": "التقنيات المستخدمة",
    "projects.modal.link": "عرض على GitHub",
    "projects.modal.team": "الفريق",
    "projects.modal.empty": "لا يوجد أعضاء فريق مضافون لهذا المشروع.",
    "projects.card.view": "اضغط لعرض التفاصيل والفريق ←",
    "projects.badge.featured": "مميز",
    "projects.meta.lead": "القائد",
    "projects.filter.all": "الكل",
    "projects.filter.drones": "الدرونز",
    "projects.filter.robotics": "الروبوتات",
    "projects.filter.ai": "الذكاء والبرمجيات",
    "projects.filter.research": "البحث",
    "projects.anchor.label": "انتقل إلى",
    "projects.anchor.overview": "نظرة عامة",
    "projects.anchor.portfolio": "شبكة المشاريع",
    "projects.anchor.stack": "التقنيات",
    "projects.focus.label": "طبيعة البناء",
    "projects.focus.title": "المشاريع هنا تبدو هندسية، لا تجميلية.",
    "projects.focus.desc": "تم تنظيم الصفحة كاستوديو عمل فعلي: أنظمة وبرمجيات ومسارات بحثية مرتبة بحسب ما تنتجه وكيف يتم بناؤها.",
    "projects.focus.systems.title": "بناء الأنظمة",
    "projects.focus.systems.desc": "طيران ذاتي وروبوتات وأعمال مدمجة تُبنى حول دورات الاختبار والقيود والأداء الميداني.",
    "projects.focus.software.title": "طبقات البرمجيات",
    "projects.focus.software.desc": "واجهات وأدوات تحكم وتدفقات مدعومة بالذكاء الاصطناعي تخدم الأجهزة الحقيقية والأعضاء والعمليات.",
    "projects.focus.research.title": "المسارات البحثية",
    "projects.focus.research.desc": "تجارب وأوراق وعمل تحقق يحوّل النماذج الأولية إلى معرفة موثقة.",
    "projects.empty.title": "لا توجد مشاريع تطابق هذا التصنيف",
    "projects.empty.body": "جرّب فئة أخرى أو ارجع إلى كامل المعرض لرؤية الامتداد التقني الأوسع.",
    "projects.apply.label": "للأعضاء",
    "projects.apply.title": "الأدوار المفتوحة في المشروع",
    "projects.apply.desc": "يمكن للأعضاء المسجلين الدخول التقديم للانضمام إلى هذا المشروع عبر أحد الأدوار التالية.",
    "projects.apply.roles": "أدوار",
    "projects.apply.applied": "تم التقديم",
    "projects.apply.allApplied": "لقد قدمت بالفعل على كل الأدوار المفتوحة في هذا المشروع.",
    "projects.apply.note": "لماذا أنت مناسب؟",
    "projects.apply.notePlaceholder": "اذكر خبرتك أو وقتك المتاح أو دافعك الذي يجعلك مناسبًا لهذا الدور.",
    "projects.apply.cta": "قدّم",
    "projects.apply.submitting": "جارٍ الإرسال…",
    "projects.apply.success": "تم إرسال الطلب. يمكن لقائد المشروع مراجعته من جهة الأعضاء.",
    "projects.apply.error": "تعذر إرسال الطلب. حاول مرة أخرى.",
    "project.status.testing": "قيد الاختبار",
    "project.status.archived": "مؤرشف",

    // ── Workshops ────────────────────────────────────────────────────────────
    "workshops.hero.label": "ورش العمل",
    "workshops.hero.title": "تعلّم · ابنِ ·",
    "workshops.hero.accent": "ابتكر",
    "workshops.hero.desc": "جلسات مباشرة وورش مسجلة تغطي الدرونز والروبوتات والذكاء الاصطناعي والتصنيع والبرمجيات.",
    "workshops.live.title": "مباشر وقادم",
    "workshops.live.sessions": "جلسات",
    "workshops.live.past": "جلسات مباشرة سابقة",
    "workshops.library.label": "التسجيلات",
    "workshops.library.title": "مكتبة الورش",
    "workshops.library.desc": "تصفح الجلسات السابقة المتاحة في أي وقت وبالوتيرة التي تناسبك.",
    "workshops.badge.completed": "مكتملة",
    "workshops.badge.upcoming": "قادمة",
    "workshops.badge.open": "التسجيل مفتوح",
    "workshops.badge.closed": "التسجيل مغلق",
    "workshops.badge.full": "اكتمل العدد",
    "workshops.live.by": "بواسطة",
    "workshops.live.registered": "مسجل",
    "workshops.live.cta": "سجل الآن ←",
    "workshops.live.fullnote": "هذه الجلسة مكتملة. تحقق لاحقًا من ورش جديدة.",
    "workshops.modal.success.title": "تم تسجيلك بنجاح",
    "workshops.modal.success.desc": "نراك في",
    "workshops.modal.success.done": "تم",
    "workshops.modal.error": "فشل التسجيل. حاول مرة أخرى.",
    "workshops.modal.live": "ورشة مباشرة",
    "workshops.modal.fullName": "الاسم الكامل *",
    "workshops.modal.fullName.placeholder": "اسمك الكامل",
    "workshops.modal.email": "البريد الإلكتروني *",
    "workshops.modal.email.placeholder": "your@email.com",
    "workshops.modal.universityId": "الرقم الجامعي",
    "workshops.modal.phone": "الجوال",
    "workshops.modal.optional": "اختياري",
    "workshops.modal.department": "القسم / التخصص",
    "workshops.modal.department.placeholder": "مثال: علوم الحاسب، الهندسة الكهربائية",
    "workshops.modal.notes": "ملاحظات",
    "workshops.modal.notes.placeholder": "أي أسئلة أو متطلبات خاصة؟ (اختياري)",
    "workshops.modal.cancel": "إلغاء",
    "workshops.modal.registering": "جارٍ التسجيل…",
    "workshops.modal.register": "سجل ←",
    "workshops.anchor.label": "انتقل إلى",
    "workshops.anchor.overview": "نظرة عامة",
    "workshops.anchor.live": "الجلسات المباشرة",
    "workshops.anchor.library": "المكتبة",
    "workshops.modes.live.title": "جلسات مباشرة",
    "workshops.modes.live.desc": "جلسات مرتبطة بوقت محدد للتسجيل والحضور والتفاعل المباشر مع المرشدين أو المقدّمين.",
    "workshops.modes.library.title": "مكتبة مسجلة",
    "workshops.modes.library.desc": "أرشيف متاح دائمًا للأعضاء الذين يريدون العودة إلى المهارات بالسرعة التي تناسبهم.",
    "workshops.modes.path.title": "مسارات المهارة",
    "workshops.modes.path.desc": "أفضل تجربة تعلم في الورش تكون تدريجية: تعلّم الأساسيات ثم طبّقها ثم عد لجلسات أعمق.",
    "workshops.empty.live.title": "لا توجد جلسات مباشرة مفتوحة الآن",
    "workshops.empty.live.body": "لا تزال الورش المسجلة متاحة بالأسفل، وستظهر الجلسات المباشرة الجديدة هنا عند نشرها.",
    "workshops.modal.at": "في",
    "workshops.recorded.empty.title": "لا توجد ورش عمل مسجلة بعد.",
    "workshops.recorded.empty.desc": "عندما يصدر قسم التطوير جلسات الورش عبر Google Drive، ستظهر هنا.",
    "workshops.category.default": "ورشة عمل",
    "workshops.presenter.default": "التطوير",
    "workshops.recorded.default": "مسجّل",
    "workshops.sessions.one": "جلسة",
    "workshops.sessions.many": "جلسات",
    "workshops.drive.label": "درايف",
    "workshops.sessions.moreDrive": "أكثر في درايف",

    // ── Footer ───────────────────────────────────────────────────────────────
    "footer.brand.name": "DRC",
    "footer.brand.subtitle": "نادي الدرونز والروبوت",
    "footer.brand.description": "نبني الجيل القادم من الأنظمة المستقلة والروبوتات التنافسية والابتكار الجوي. نحن نهندس المستقبل.",
    "footer.brand.arabic": "نادي الدرونز والروبوت",
    "footer.club.title": "النادي",
    "footer.club.about": "عن النادي",
    "footer.club.projects": "المشاريع",
    "footer.club.events": "الفعاليات",
    "footer.club.team": "الفريق",
    "footer.connect.title": "تواصل",
    "footer.connect.join": "انضم إلينا",
    "footer.connect.twitter": "تويتر / X",
    "footer.connect.instagram": "إنستغرام",
    "footer.connect.linkedin": "لينكدإن",
    "footer.connect.tiktok": "تيك توك",
    "footer.connect.empty": "حسابات التواصل قادمة قريبًا.",
    "footer.contact.title": "للشركات والشركاء",
    "footer.contact.desc": "تواصلوا مع DRC للزيارات والرعايات والتعاون والعروض والفرص التقنية للطلاب.",
    "footer.bottom.copyright": "جميع الحقوق محفوظة.",
    "footer.bottom.status": "نستقبل أعضاء جدد",

    // ── Login ─────────────────────────────────────────────────────────────────
    "login.title": "أهلاً بعودتك",
    "login.subtitle": "سجّل دخولك إلى بوابة أعضاء DRC",
    "login.email": "البريد الإلكتروني",
    "login.password": "كلمة المرور",
    "login.submit": "تسجيل الدخول",
    "login.forgot": "نسيت كلمة المرور؟",
    "login.show_password": "إظهار كلمة المرور",
    "login.hide_password": "إخفاء كلمة المرور",
    "login.back": "→ العودة للموقع",
    "login.or": "أو",
    "login.demo.show": "دخول سريع بحساب تجريبي",
    "login.demo.hide": "إخفاء الحسابات التجريبية",
    "login.error.device": "جهاز جديد. تحقق من بريدك الإلكتروني لتأكيد الجهاز.",
    "login.error.invalid": "بيانات غير صحيحة.",
    "login.info.setup": "مرحبًا! تحقق من بريدك الإلكتروني للحصول على رابط إعداد كلمة المرور. صالح لمدة 24 ساعة.",
  },
};

export function LanguageProvider({ children, initialLang = "en" }: { children: React.ReactNode; initialLang?: Lang }) {
  const { user, isLoading } = useAuth();
  const [lang, setLang] = useState<Lang>(initialLang);
  const [overrides, setOverrides] = useState<Record<string, SiteContentRow>>({});
  const [accountReady, setAccountReady] = useState(false);

  // Sync with localStorage on mount and listen for cross-tab changes
  useEffect(() => {
    const stored = localStorage.getItem(LANG_STORAGE_KEY);
    if (stored === "ar" || stored === "en") {
      setLang(stored);
    }

    const handleStorage = (event: StorageEvent) => {
      if (event.key === LANG_STORAGE_KEY) {
        const v = event.newValue;
        if (v === "ar" || v === "en") setLang(v);
      }
    };
    const handleLangChange = () => {
      const v = localStorage.getItem(LANG_STORAGE_KEY);
      if (v === "ar" || v === "en") setLang(v);
    };

    window.addEventListener("storage", handleStorage);
    window.addEventListener(LANG_EVENT, handleLangChange);
    return () => {
      window.removeEventListener("storage", handleStorage);
      window.removeEventListener(LANG_EVENT, handleLangChange);
    };
  }, []);

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    try {
      localStorage.setItem(LANG_STORAGE_KEY, lang);
      document.cookie = `${LANG_STORAGE_KEY}=${lang}; path=/; max-age=${365 * 24 * 60 * 60}; samesite=lax`;
      if (user?.id) {
        localStorage.setItem(`${LANG_STORAGE_KEY}:${user.id}`, lang);
      }
    } catch {}
  }, [lang, user?.id]);

  useEffect(() => {
    if (isLoading) return;

    if (!user?.id) {
      setAccountReady(true);
      return;
    }

    let cancelled = false;
    setAccountReady(false);

    try {
      const scoped = localStorage.getItem(`${LANG_STORAGE_KEY}:${user.id}`);
      if ((scoped === "ar" || scoped === "en") && scoped !== lang) {
        setLang(scoped);
      }
    } catch {}

    fetch("/api/members/preferences", { cache: "no-store" })
      .then((res) => res.json())
      .then((body) => {
        if (cancelled) return;
        const preferredLang = body?.data?.preferences?.language;
        if (preferredLang === "ar" || preferredLang === "en") {
          setLang(preferredLang);
          try {
            localStorage.setItem(`${LANG_STORAGE_KEY}:${user.id}`, preferredLang);
          } catch {}
        }
      })
      .catch(() => {})
      .finally(() => {
        if (!cancelled) setAccountReady(true);
      });

    return () => {
      cancelled = true;
    };
  }, [isLoading, user?.id]);

  useEffect(() => {
    if (!accountReady || !user?.id) return;

    void fetch("/api/members/preferences", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ language: lang }),
    }).catch(() => {});
  }, [accountReady, lang, user?.id]);

  useEffect(() => {
    let cancelled = false;

    fetch("/api/site-content", { cache: "no-store" })
      .then((res) => res.json())
      .then((body) => {
        if (cancelled) return;
        const rows = Array.isArray(body?.data) ? (body.data as SiteContentRow[]) : [];
        const next: Record<string, SiteContentRow> = {};
        for (const row of rows) {
          next[row.key] = row;
        }
        setOverrides(next);
      })
      .catch(() => {
        if (!cancelled) setOverrides({});
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const toggleLang = () => {
    const nextLang = lang === "en" ? "ar" : "en";
    setLang(nextLang);
    try {
      localStorage.setItem(LANG_STORAGE_KEY, nextLang);
      window.dispatchEvent(new Event(LANG_EVENT));
    } catch {}
  };

  const t = (key: string) => {
    const row = overrides[key] ?? overrides[`${key}.text`];
    const override = lang === "ar" ? row?.ar : row?.en;
    if (override && override.trim().length > 0) return override;
    const fallback = (baseTranslations[lang] as Record<string, string>)[key];
    return fallback ?? key;
  };

  return <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
